### ISSUE TITLE
Organize October Demo Night

### ISSUE THREAD

**Issue by selynna** [hackclub-archive/events#1]
This issue is tracking all the issues we have for the August Demo Night and will be updated regularly.
- [x] Find venue (@ssun098, #6)
- [x] Find another person to train for organizing Demo Night (@ssun098, #7)
- [x] Create Facebook/Eventbrite events (@ssun098, #8, blocking on #6)
- [x] Find keynote speaker (@saescapa, #9)
- [x] Find short-talk speaker (@ssun098, #10)
- [x] Schedule (@ssun098, #11)
- [ ] Sign ups (@ssun098, #13)
- [ ] Sign ups from people who want to demo (@ssun098, #12)
- [x] Update subdomain for Demo Night (@MaxWofford, #17, blocking on #8)

**Comment by maxwofford** [comment]
Closed because this is no longer being organized.
